import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import test from 'node:test'

test('minimal web client keeps receiver monitoring and one unified activity workspace', () => {
  const root = path.resolve(__dirname, '../..')
  const html = readFileSync(path.join(root, 'public/index.html'), 'utf8')
  const script = readFileSync(path.join(root, 'public/main.js'), 'utf8')

  assert.doesNotMatch(html, /Listen live/)
  assert.doesNotMatch(html, />Recent radio</)
  assert.match(html, /Voice watch · Slot A/)
  assert.match(html, /Digital watch · Slot B/)
  assert.match(html, /id="preset-standard"[^>]*>16 \+ DSC 70</)
  assert.match(html, /id="preset-slot-a-16"[^>]*>Slot A · 16</)
  assert.match(html, /id="preset-slot-b-70"[^>]*>Slot B · 70</)
  assert.match(html, />Scan</)
  assert.match(html, /Recent activity/)
  assert.match(html, /DSC calls/)
  assert.match(html, /United States \+ Canada/)
  assert.match(html, /No transmit controls exist/)
  assert.match(html, /Rolling buffer/)
  assert.match(html, />Activity</)
  assert.match(html, /Frequency activity/)
  assert.match(html, /Storage &amp; status/)
  assert.match(html, /Listening &amp; tuning/)
  assert.match(html, /Activity \/ playback squelch/)
  assert.match(html, /processing-panel/)
  assert.match(html, /frequency-map/)
  assert.match(html, /Listening — no bursts above squelch yet/)
  assert.match(html, /<option value="raw">Raw<\/option>/)
  assert.doesNotMatch(html, />Natural<\/option>/)
  assert.match(html, /Voice focus/)
  assert.match(html, /Comfort · adaptive hiss reduction/)
  assert.match(html, /Maximum hiss reduction/)
  assert.match(html, /Strong static reduction/)
  assert.match(html, /Speech denoise · RNNoise/)
  assert.match(html, /Delete all recent audio\?/)
  assert.match(html, /clear-replay-dialog/)
  assert.match(html, /Transcribe voice/)
  assert.match(html, /transcription-model/)
  assert.match(html, /transcription-threads/)

  assert.match(script, /request\('slots'/)
  assert.match(script, /applyChannelPreset/)
  assert.match(script, /slotAChannel\.value = '16'/)
  assert.match(script, /slotBChannel\.value = '70'/)
  assert.match(script, /slotConfigurationPending/)
  assert.match(script, /document\.activeElement !== slotAChannel/)
  assert.match(script, /const selection = \{ mode: slotAMode\.value, slotAChannel: slotAChannel\.value, slotBChannel: slotBChannel\.value \}/)
  assert.match(script, /single-frequency; pauses Slot B \+ DSC/)
  assert.match(script, /availableSlotB/)
  assert.match(script, /Primary watch/)
  assert.match(script, /Marine voice · numeric order/)
  assert.match(script, /Coast \/ duplex · pauses Slot B/)
  assert.match(script, /Weather · pauses Slot B/)
  assert.match(script, /channel\.availableSlotB !== false/)
  assert.match(script, /MINIMUM_REPLAY_SIGNAL_SECONDS/)
  assert.match(script, /renderFrequencyMap/)
  assert.match(script, /timelineReceiverRows/)
  assert.match(script, /frequency-floor/)
  assert.match(script, /floorMarks/)
  assert.match(script, /activityRuns/)
  assert.match(script, /frequency-burst/)
  assert.match(script, /channelFrequency/)
  assert.match(script, /timelineAudio\.addEventListener\('ended'/)
  assert.match(script, /cleanup=\$\{encodeURIComponent\(timelineCleanup\.value\)\}/)
  assert.match(script, /replay\/\$\{segment\.id\}\/continuous\.wav/)
  assert.match(script, /timelineAwaitingChannel/)
  assert.match(script, /groupReplaySessions/)
  assert.match(script, /groupArchiveSessions/)
  assert.match(script, /renderProcessingQueue/)
  assert.match(script, /status\.slots\.B\.kind === 'dsc'/)
  assert.match(script, /UI_VERSION|CLIENT_BUILD/)
  assert.match(script, /SESSION_BREAK_SECONDS = 6/)
  assert.match(script, /transcript-session\.wav\?ids=/)
  assert.match(script, /hasPlayingAudio/)
  assert.match(script, /pauseOtherAudio/)
  assert.match(script, /document\.addEventListener\('play'/)
  assert.match(script, /audio !== activeAudio && !audio\.paused/)
  assert.match(script, /archiveRenderSignature/)
  assert.match(script, /!hasPlayingAudio\(archiveList\)/)
  assert.match(script, /request\('transcripts\?limit=500'/)
  assert.match(script, /document\.createElement\('details'\)/)
  assert.match(script, /archive-log-line/)
  assert.match(script, /Copy transcript/)
  assert.match(script, /Transcript reader/)
  assert.match(script, /transcript-session\.opus\?ids=/)
  assert.match(script, /Sarah · cached Opus/)
  assert.match(script, /Whisper takes priority/)
  assert.doesNotMatch(script, /SpeechSynthesisUtterance|speechSynthesis/)
  assert.match(script, /!hasPlayingAudio\(archiveList\)/)
  assert.match(script, /Download current playback/)
  assert.match(script, /Original WAV/)
  assert.match(script, /vhf-whisper-runtime/)
  assert.match(script, /availableModels/)
  assert.match(script, /saveTranscriptionRuntime/)
  assert.doesNotMatch(script, /push.?to.?talk|\bptt\b|transmit/i)
})

test('each transcript line deep-links to audio and a waveform marker', () => {
  const root = path.resolve(__dirname, '../..')
  const script = readFileSync(path.join(root, 'public/main.js'), 'utf8')
  const css = readFileSync(path.join(root, 'public/styles.css'), 'utf8')

  assert.match(script, /transcriptMomentId/)
  assert.match(script, /transcript-time-link/)
  assert.match(script, /transcript-marker/)
  assert.match(script, /dataset\.audioOffset/)
  assert.match(script, /window\.history\.pushState/)
  assert.match(script, /openTranscriptFromHash/)
  assert.match(script, /window\.addEventListener\('hashchange'/)
  assert.match(script, /selectTranscriptMoment/)
  assert.match(script, /offset \+= candidate\.durationSeconds/)
  assert.match(script, /renderArchiveWaveform/)
  assert.match(script, /wavSamples/)
  assert.match(css, /\.transcript-marker/)
  assert.match(css, /\.archive-log-line:target/)
})

test('each archived recording has independent non-destructive squelch and cleanup', () => {
  const root = path.resolve(__dirname, '../..')
  const script = readFileSync(path.join(root, 'public/main.js'), 'utf8')

  assert.match(script, /Playback squelch/)
  assert.match(script, /Background noise/)
  assert.match(script, /<option value="raw">Raw<\/option>/)
  assert.doesNotMatch(script, />Natural<\/option>/)
  assert.match(script, /Off \/ raw/)
  assert.match(script, /Strong reduction/)
  assert.match(script, /Comfort · adaptive hiss reduction/)
  assert.match(script, /Maximum hiss reduction/)
  assert.match(script, /Speech denoise · RNNoise/)
  assert.match(script, /cleanup=\$\{encodeURIComponent\(cleanup\)\}&squelch=\$\{encodeURIComponent\(squelch\)\}/)
  assert.match(script, /audio\.currentTime/)
  assert.match(script, /download\.href = source/)
})
