import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import test from 'node:test'

test('dedicated web client exposes dual receiver slots and continuous replay without transmit controls', () => {
  const root = path.resolve(__dirname, '../..')
  const html = readFileSync(path.join(root, 'public/index.html'), 'utf8')
  const script = readFileSync(path.join(root, 'public/main.js'), 'utf8')
  assert.doesNotMatch(html, /Listen live/)
  assert.match(html, /Slot A/)
  assert.match(html, /Slot B/)
  assert.match(html, />Scan</)
  assert.match(html, /Recent radio/)
  assert.match(html, /Digital selective calls/)
  assert.match(html, /United States \+ Canada/)
  assert.match(html, /No transmit controls exist/)
  assert.match(script, /request\('slots'/)
  assert.match(script, /single-frequency; pauses Slot B \+ DSC/)
  assert.match(script, /CHANNEL 70 · PAUSED FOR WEATHER/)
  assert.match(script, /availableSlotB/)
  assert.match(script, /replay/)
  assert.match(script, /dsc/)
  assert.match(script, /activity-chart/)
  assert.match(script, /seconds of detected sound/)
  assert.match(script, /MINIMUM_REPLAY_SIGNAL_SECONDS/)
  assert.match(script, /No radio activity passes squelch/)
  assert.match(html, /Radio timeline/)
  assert.match(html, /Playback is stitched seamlessly through stored audio and the live edge/)
  assert.match(html, /PAST TWO HOURS/)
  assert.match(html, /Frequency activity/)
  assert.match(html, /frequency-map/)
  assert.match(html, /Listening — no bursts above squelch yet/)
  assert.match(html, /below squelch/)
  assert.match(script, /renderFrequencyMap/)
  assert.match(script, /timelineReceiverRows/)
  assert.match(script, /frequency-floor/)
  assert.match(script, /floorMarks/)
  assert.match(script, /activityRuns/)
  assert.match(script, /frequency-burst/)
  assert.match(script, /channelFrequency/)
  assert.match(script, /timelineAudio\.addEventListener\('ended'/)
  assert.match(script, /replay\/\$\{segment\.id\}\/continuous\.wav/)
  assert.match(script, /timelineAwaitingChannel/)
  assert.match(script, /Waiting for \$\{channelDisplay\(timelineAwaitingChannel\)\} audio/)
  assert.match(script, /segment\.slot === 'A' && segment\.channel === timelineAwaitingChannel/)
  assert.match(script, /channel\.weather \? `\$\{channel\.label\} · \$\{channel\.purpose\}`/)
  assert.match(script, /channelFrequencyDisplay\(segment\.channel\)/)
  assert.match(html, /Delete all recent radio\?/)
  assert.match(html, /clear-replay-dialog/)
  assert.match(script, /replay-delete/)
  assert.match(script, /for \(const id of segment\.ids\) await request\(`replay\/\$\{id\}`/)
  assert.match(script, /groupReplaySessions/)
  assert.match(script, /groupArchiveSessions/)
  assert.match(script, /SESSION_BREAK_SECONDS = 6/)
  assert.match(script, /replay-session\.wav\?ids=/)
  assert.match(script, /transcript-session\.wav\?ids=/)
  assert.doesNotMatch(script, /confirm\('Clear the private rolling VHF replay buffer/)
  assert.match(script, /timelineWaitingAtEdge/)
  assert.match(script, /selectLatestActiveTimeline/)
  assert.match(script, /Waiting for receiver status/)
  assert.match(script, /if \(!timelineActiveSlotAChannel\)/)
  assert.match(script, /segment\.channel === timelineActiveSlotAChannel/)
  assert.match(html, /Transcribe voice/)
  assert.match(html, /transcription-model/)
  assert.match(html, /transcription-threads/)
  assert.match(html, /Transcript archive/)
  assert.match(html, /30 DAYS · 100 MIB MAXIMUM/)
  assert.match(script, /request\('transcripts\?limit=500'/)
  assert.match(script, /vhf-whisper-runtime/)
  assert.match(script, /availableModels/)
  assert.match(script, /saveTranscriptionRuntime/)
  assert.doesNotMatch(script, /push.?to.?talk|\bptt\b|transmit/i)
})
