import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import test from 'node:test'

test('dedicated web client exposes dual receiver slots and continuous replay without transmit controls', () => {
  const root = path.resolve(__dirname, '../..')
  const html = readFileSync(path.join(root, 'public/index.html'), 'utf8')
  const script = readFileSync(path.join(root, 'public/main.js'), 'utf8')
  assert.doesNotMatch(html, /Listen live/)
  assert.match(html, /Slot A/)
  assert.match(html, /Slot B/)
  assert.match(html, />Scan</)
  assert.match(html, /Recent radio/)
  assert.match(html, /Digital selective calls/)
  assert.match(html, /United States \+ Canada/)
  assert.match(html, /No transmit controls exist/)
  assert.match(script, /request\('slots'/)
  assert.match(script, /replay/)
  assert.match(script, /dsc/)
  assert.match(script, /activity-chart/)
  assert.match(script, /seconds of detected sound/)
  assert.match(script, /MINIMUM_REPLAY_SIGNAL_SECONDS/)
  assert.match(script, /No radio activity passes squelch/)
  assert.match(html, /Radio timeline/)
  assert.match(html, /PAST TWO HOURS/)
  assert.match(html, /Frequency activity/)
  assert.match(html, /frequency-map/)
  assert.match(script, /renderFrequencyMap/)
  assert.match(script, /activityRuns/)
  assert.match(script, /frequency-burst/)
  assert.match(script, /channelFrequency/)
  assert.match(script, /timelineAudio\.addEventListener\('ended'/)
  assert.match(html, /Delete all recent radio\?/)
  assert.match(html, /clear-replay-dialog/)
  assert.match(script, /replay-delete/)
  assert.match(script, /request\(`replay\/\$\{segment\.id\}`/)
  assert.doesNotMatch(script, /confirm\('Clear the private rolling VHF replay buffer/)
  assert.match(script, /timelineWaitingAtEdge/)
  assert.match(html, /Transcribe voice/)
  assert.match(html, /Transcript archive/)
  assert.match(html, /30 DAYS · 100 MIB MAXIMUM/)
  assert.match(script, /request\('transcripts\?limit=500'/)
  assert.match(script, /transcripts\/\$\{record\.id\}\.wav/)
  assert.match(script, /vhf-whisper-runtime/)
  assert.doesNotMatch(script, /push.?to.?talk|\bptt\b|transmit/i)
})
